stages:
  - clean

clean_k8s_cluster:
  stage: clean
  script:
    - set +o pipefail
    - . /home/gitlab-runner/coe-cluster-config/st-gitlab-k8s-01/env_st-gitlab-k8s-01.sh # get access configs for the cluster
    - kubectl get pods --no-headers --all-namespaces | 
      grep -E 'ImagePullBackOff|ErrImagePull|Evicted' | 
      awk '{print $2 " --namespace=" $1}' | 
      xargs --no-run-if-empty -n2 kubectl describe pods
    - kubectl get namespaces --no-headers -o custom-columns=":metadata.name,:.metadata.creationTimestamp" | 
      grep -v 'default\|kube-public\|kube-system' | 
      awk '$2 <= "'$( date --utc -d "3 days ago" +"%Y-%m-%dT%H:%M:%SZ" )'" { print $1 }' | 
      xargs --no-run-if-empty kubectl delete namespaces ; echo $?
  dependencies: []
  tags:
    - shell-with-docker
    - k8s_node
  only:
    - fix_clean_k8s_stage
